plugins:
  - "@trivago/prettier-plugin-sort-imports"
printWidth: 120
proseWrap: "always"
trailingComma: "all"

overrides:
  - files: ["*.ts", "*.tsx"]
    options:
      importOrderParserPlugins: ["typescript"]
      importOrderSeparation: true
      importOrderSortSpecifiers: true
      parser: "typescript"
